# This compose file is meant to be used for developing on antidote-web or one of the related projects
# such as antidote-ui-components. By default, it starts a single container for the web front end and
# assumes the rest is running elsewhere. However, if you wish, you can un-comment the additional sections
# below to get additional development-time tools.

version: "3.7"
services:

  # This section will build the antidote-web container from source, which also pulls in all dependencies listed in package.json
  # See README for more details.
  antidote-web:
    build:
      context: .
      dockerfile: ./hack/Dockerfile-dev
    environment:
      WEBSSH2_LOCATION: 'http://127.0.0.1:8081'
    ports:
      - "8080:80"
    volumes:
      - './src:/usr/share/nginx/html'
  # WebSSH2 is also required for terminal functionality - provides a websocket-to-ssh proxy for the front-end
  webssh2:
    image: "antidotelabs/webssh2:ping-timeout"
    ports:
      - "8081:8080"
    volumes:
      - ./hack/websshconfig.json:/usr/src/config.json

  # This section runs an instance of antidoted here with only the API service enabled. You can then use
  # "antictl" to create mock instances of livelessons with arbitrary data for testing antidote-web
  # functionality on top of the Antidote API
  antidote-core:
    image: "antidotelabs/antidote-core:latest"
    depends_on:
    - nats-server
    ports:
      - "8086:8086"   # REST
      - "50099:50099" # gRPC
    volumes:
      - ./hack:/hack

      # NOTE - must first clone https://github.com/nre-learning/antidote-test-curriculum as a sibling directory to antidote-web.
      #
      # You are welcome to use another antidote curriculum, such as NRE Labs, but you'll have to change the mapping here.
      - ../antidote-test-curriculum:/antidote-test-curriculum
    command: antidoted --config /hack/antidoted-config.yaml
  nats-server:  # Pub/sub server required by antidoted
    image: "nats"
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"

  # Some example endpoints are provided here for convenience. Note that the IP address provided in the mock livelesson in the `hack/` directory is the docker bridge,
  # which will allow connectivity here over the mapped port.
  linux1:
    image: "antidotelabs/utility"
    ports:
    - "2222:22"
  # webserver1:
  #   image: "antidotelabs/webserver"
  #   ports:
  #     - "8090:8080"
