version: "3.7"
services:

  # Primary antidote-web and guac services
  antidote-web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GUACD_HOSTNAME: 'guacd'
      POSTGRES_HOSTNAME: 'na'
      POSTGRES_DATABASE: 'na'
      POSTGRES_USER: 'na'
      POSTGRES_PASSWORD: 'na'
    ports:
      - "8080:8080"
  guacd: 
    image: "guacamole/guacd"

  # Fake Syringe API (no Kubernetes integration)
  syringe-mock:
    image: "antidotelabs/syringe:latest"
    command: syringed-mock
    ports: 
      - "8086:8086"

  # Some endpoints to connect to (The fake data from Syringe will point to these)
  linux1:
    image: "antidotelabs/utility"
  webserver1:
    image: "antidotelabs/webserver"
    environment:
      SYRINGE_FULL_REF: 1-m0w5c6xzceintfat-ns-webserver1
    ports:
      - "8090:8080"
