# This is a DEVELOPMENT dockerfile, and therefore includes no npm build
# steps. The build steps are accomplished by the dev.sh script in the
# /src/scripts directory.

FROM nginx
COPY launch.sh /
CMD ["/launch.sh"]
